spring:
  application:
    name: eureka-client2

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    serviceUrl:
      defaultZone: http://172.16.20.212:8765/eureka/
