spring:
  application:
    name: dubbo-client2

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    serviceUrl:
      defaultZone: http://172.16.20.212:8765/eureka/

dubbo:
  scan:
    base-packages: com.sekorm.**
  consumer:
    check: false
  protocol:
    name: dubbo
    port: ${random.int(30000)}
  registry:
    address: zookeeper://172.16.20.213:2181
    group: dev